### ISSUE TITLE
Cant use spacebar or numbers in Rednet Program

### ISSUE THREAD

**Issue by Smallsanta10** [civilwargeeky/Civils_Progs#10]

**Comment by civilwargeeky** [comment]
Hello,
Thank you for reporting this bug, but I have already fixed it in 8ba1d989cba6d1563c4d8954e6e5736ca2bf5eb9.
You can download the version which is fixed via the link in this [forum post.](http://www.computercraft.info/forums2/index.php?/topic/5681-variable-size-quarry-now-with-super-ore-quarry%e2%84%a2/page__view__findpost__p__279565)
If you still have issue, please provide more detail.
