### ISSUE TITLE
i was trying to reach out to you

### ISSUE THREAD

**Issue by Nuclearpotato69** [civilwargeeky/Civils_Progs#13]
i was trying to do what the title says but cant make a account of the forum and wanted to make a cool suggestion 

so my suggestion is it would be cool to add support to make it so you can control multiple turtles from the pc and they could all take chunks of the quarry and it would be nice if also you had more control from the computer over the turtles thanks

also i would legit pay for a program like this (if i had some money to spend ofc)

**Comment by civilwargeeky** [comment]
Hello! Apologies, I have been swamped the past week.
I think that would be a good idea! However, I have a lot of other personal projects going on right now, and wouldn't be able to get to your ideas in a timely manner.
If you really want this to happen, a lot of the fun of lua and computercraft is that it's pretty easy to learn to code and write your own programs! You could try writing your own script to interact with distant turtles, and a turtle script that will receive these interactions, go to a location, and call my program.

Thank you for reaching out! Sorry I won't be of more help.

**Comment by Nuclearpotato69** [comment]
its ok tysm tho
