### ISSUE TITLE
feature request for query: crafty mining turtle

### ISSUE THREAD

**Issue by frankenstein91** [civilwargeeky/Civils_Progs#6]
Hello
can you modifie your script to compress Cobblestone?
http://ftbwiki.org/Compressed_Cobblestone

**Comment by civilwargeeky** [comment]
I'm sorry, but I don't think that I will be adding this feature right now. (Or the 2 months I didn't see this...).
For the possible future, how would you propose that this works? Would it compress the cobble when it goes to drop stuff off? Would it have to store the cobblestone in another chest temporarily? I'm not really sure how I would go about implementing this.
