### ISSUE TITLE
Quarry Program doesn´t start

### ISSUE THREAD

**Issue by Phill93** [civilwargeeky/Civils_Progs#7]
The quarry program doesn´t start with the error: quarry:18: attempt to call nil
Im using computercraft 1.75 (here you can find the modlist https://minecraft.phill93.de/modlist.txt)

**Comment by civilwargeeky** [comment]
I'm sorry, but whatever mod is screwing up my program is not computercraft. Unless you can tell me why all the functions I use no longer exist, I cannot fix anything.
![2016-01-25_15 54 47](https://cloud.githubusercontent.com/assets/4176360/12565869/4b193a44-c37c-11e5-9845-8dada05850f9.png)
![2016-01-25_15 56 18](https://cloud.githubusercontent.com/assets/4176360/12565866/4b16d31c-c37c-11e5-9991-7748304220da.png)
![2016-01-25_15 56 35](https://cloud.githubusercontent.com/assets/4176360/12565870/4b19853a-c37c-11e5-9bb5-58f97108fed2.png)
![2016-01-25_15 56 54](https://cloud.githubusercontent.com/assets/4176360/12565867/4b1880f4-c37c-11e5-9560-3a55f359f0b5.png)
![2016-01-25_15 57 02](https://cloud.githubusercontent.com/assets/4176360/12565868/4b18cf78-c37c-11e5-87c3-7ca3b4fca66e.png)
Cannot reproduce.
